config/routes.rb
Rails.application.routes.draw do

  resources :tournaments do
    get 'search', on: :collection
  end
  
  resources :tournaments do
    resources :teams do
      resources :roosters
    end
  end

  resources :tournaments do
    resources :opponent_teams do
      resources :opponent_roosters
    end
  end

  resources :tournaments do
    resources :events do
      resources :team_line_ups
      resources :opponent_team_line_ups
    end
  end

  resources :tournaments do
    resources :events do
      get 'start', on: :member
      get 'resume', on: :member
      patch 'update_rooster_position', on: :member
      patch 'play', on: :member
    end
  end


  resources :tournaments do
    resources :invitations, only: [:new, :create]
  end
  
  resources :invitations, only: [:new, :create] do
    member do
      get 'accept'
    end
  end


resources :pitching_stats
resources :batting_stats
get 'my_events', to: 'events#my_events'


  root 'pages#home'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  get "/verify" => "verify#edit", :as => "verify"
  get "/verify" => "verify#new", :as => "new_verify"
  put "/verify" => "verify#update", :as => "update_verify"
  post "/verify" => "verify#create", :as => "resend_verify"
  resources :users, only: [:index,:destroy]
  
end

app/models/opponent_team.rb
class OpponentTeam < ApplicationRecord
    belongs_to :user
    belongs_to :tournament
    has_many :opponent_roosters, dependent: :destroy
    has_many :event,dependent: :destroy
    has_many :opponent_team_line_up,dependent: :destroy
    has_one_attached :image ,dependent: :destroy
    validates :name, :short_name, presence: true
    has_many :batting_stats	, dependent: :destroy
    has_many :pitching_stats, dependent: :destroy	


    before_create :set_user_id
    private
  
    def set_user_id
      self.user_id = user.id if user
    end
end

app/controllers/opponent_teams_controller.rb
class OpponentTeamsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: %i[ index show]
  before_action :set_opponent_team, only: %i[ show edit update destroy ]
  before_action :set_tournament

  def index
    if current_user.nil?
      @opponent_opponent_team  = OpponentTeam .all
    else
      @opponent_team  = OpponentTeam.where(user_id:current_user.id)
    end
  end

  def show
    @tournament = Tournament.find(params[:tournament_id]) 
    @opponent_team = @tournament.opponent_teams.find(params[:id]) 
    ActiveStorage::Current.url_options = {
      host: request.base_url
    }
  end

  def new
    @tournament = Tournament.find(params[:tournament_id])
    @opponent_team = OpponentTeam.new
  end

  def edit
    @tournament = Tournament.find(params[:tournament_id])
    @opponent_team = @tournament.opponent_teams.find(params[:id])
  end

  def create
    @opponent_team = current_user.opponent_teams.build(opponent_team_params.merge(tournament_id:@tournament.id ))
    if @opponent_team.save
      flash[:notice] = "Opponent Team was successfully created."
      redirect_to tournament_opponent_team_path(@tournament, @opponent_team)
    else
      render "new"
    end
  end

  def update
    if @opponent_team.update(opponent_team_params)
      flash[:notice] = "Opponent Team was successfully updated."
      redirect_to tournament_opponent_team_path(@tournament, @opponent_team)
    else
      render "edit"
    end
  end

  def destroy
    @opponent_team.destroy
    flash[:notice] = "Opponent Team was successfully deleted."
    redirect_to tournament_opponent_teams_path
  end

  private
    def set_opponent_team
      @opponent_team = OpponentTeam.find(params[:id])
    end

    def set_tournament
      @tournament = Tournament.find(params[:tournament_id])
    end

    def opponent_team_params
      params.require(:opponent_team).permit(:name, :short_name,:user_id,:tournament_id ,:team_id, :image) 
    end
end

app/helpers/opponent_team_helper.rb
module OpponentTeamHelper
end

app/views/opponent_teams/_form.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
    <div class="border rounded p-4"> 
      <%= form_with model: [@tournament, @opponent_team] do |form| %>    
        <div class="form-group">
        <%= form.label :full_name %><span class="required">*</span>
        <%= form.text_field :name, class: "form-control", required: true, autocomplete: 'off' %>
        <% if @opponent_team.errors[:name].any? %>
        <div class="error-message", style="color: #f4340a;">
          <b><%= "name " + @opponent_team.errors[:name].join(", ") %></b>
        </div>
      <% end %>
      </div>
      
      <div class="form-group">
      <div style = "display: inline;"><%= form.label :short_name %><span class="required">*</span></div>
      <%= form.text_field :short_name, class: "form-control", required: true, autocomplete: 'off' %>
      <% if @opponent_team.errors[:short_name].any? %>
      <div class="error-message", style="color: #f4340a;">
        <b><%= "short_name " + @opponent_team.errors[:short_name].join(", ") %></b>
      </div>
      <% end %>
      </div>
      
      <div class="form-group">
      <%= form.label :image %>
      <%= form.file_field :image, class: "form-control-file" %>
    </div>
      
        <div class="row">
          <div class="col-md-12 text-center">
            <div class="d-grid gap-2">
            <% if @opponent_team.persisted? %>
              <%= form.submit "Update", class: "btn btn-outline-primary " %>
            <% else %>
            <%= form.submit "Create", class: "btn btn-outline-primary " %>
            <% end %>
              <%= link_to "Back", tournament_path(@tournament), class: "btn btn-outline-primary btn-sm" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    </div>
  </div>
</div>

app/views/opponent_teams/_opponent_team.html.erb
<div id="<%= dom_id opponent_team %>">
  <p>
    <strong>Name:</strong>
    <%= opponent_team.name %>
  </p>

  <p>
    <strong>Short name:</strong>
    <%= opponent_team.short_name %>
  </p>

</div>

app/views/opponent_teams/edit.html.erb
<h1 style="text-align:center"> Edit Opponent_Team </h1> 


<%= render "form" %>

app/views/opponent_teams/index.html.erb
<div class="container mt-6">
  <h1 class="text-center mb-4">TEAMS</h1>

  <div class="d-flex justify-content-between align-items-center mb-3">
    <!-- Search Bar -->
    <div class="input-group">

      <input type="text" class="form-control" placeholder="Search..." aria-label="Search" aria-describedby="basic-addon2">
      <div class="input-group-append">
        <button class="btn btn-outline-secondary" type="button">Search</button>
      </div>
      
    </div>

    <%= link_to "New Opponent Team", new_tournament_opponent_team_path, class: "btn btn-success" %>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @opponent_teams.each do |opponent_team| %>
        <tr>
          <td><%= opponent_team.name %></td>
          <td>
            <%= link_to "Show", tournament_opponent_teams_path, class: "btn btn-primary btn-sm" %> 
            <% if false %>
            <% if can? :update, team %>
              <%= link_to "Edit", edit_tournament_opponent_team_path, class: "btn btn-secondary btn-sm" %> 
            <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/opponent_teams/new.html.erb
<h1 style="text-align:center"> New Opponent Team </h1> 



<%= render "form" %>

app/views/opponent_teams/show.html.erb
  
</div>

<div class="container">
  <div style="display: flex; align-items: center;">
  <%= image_tag("team.png", alt: "team", style: "width: 60px; height: 60px; object-fit: cover;") %>
  <h2 style="margin-left: 10px;"><%= @opponent_team.name %></h2>

</div>

<%= render @opponent_team %>

  <div class="actions">
 
            <%= link_to new_tournament_opponent_team_opponent_rooster_path(@opponent_team.tournament, @opponent_team) do %>
              <%= image_tag("addroaster.png", alt: "edit", style: "width: 25px; height: 25px; object-fit: cover;") %> |
              <% end %>
            <%#= link_to "Add New Rooster", new_tournament_team_rooster_path(@team.tournament, @team), class: "btn btn-success" %> 



     
            <%= link_to edit_tournament_opponent_team_path(@opponent_team.tournament, @opponent_team) do %>
              <%= image_tag("edit.png", alt: "edit", style: "width: 20px; height: 20px; object-fit: cover;") %> |
              <% end %>
              <%#= link_to "Edit this team", edit_tournament_team_path(@team.tournament, @team), class: "btn btn-primary" %> 
              <%= link_to tournaments_path(@tournament) do %>
                <%= image_tag("back.png", alt: "back", style: "width: 20px; height: 20px; object-fit: cover;") %> |
                <% end %>
                <div style=" margin-left:105px; margin-top: -25px;">
            <%= button_to tournament_path,method: :delete, data: { confirm: "Are you sure?" } do %>
              <%= image_tag("empty.png", alt: "edit", style: "width: 20px; height: 20px; object-fit: cover;") %> 
              <% end %>
              <%#= button_to "Destroy", [@team.tournament, @team], method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
 </div>


            <%#= link_to "Back to Tournament", tournament_path(@tournament), class: "btn btn-secondary" %>
    
  </div>
  <br/>
  <h2>Rosters</h2>
  <table class="table">
  <thead>
    <tr>
      <th>Roosters</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @opponent_team.opponent_roosters.each do |opponent_rooster| %>
      <tr>
        <td>
          <p><%= opponent_rooster.name %></p>
        </td>
        <td>
        <%= link_to tournament_opponent_team_opponent_rooster_path(@tournament,@opponent_team,opponent_rooster) do %>
          <%= image_tag("show.png", alt: "show", style: "width: 20px; height: 20px; object-fit: cover;") %> 
          <% end %>
          <%#= link_to "Show", tournament_team_rooster_path(@tournament,@team,rooster), class: "btn btn-success" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


  
</div>