config/routes.rb
Rails.application.routes.draw do

  resources :tournaments do
    get 'search', on: :collection
  end
  
  resources :tournaments do
    resources :teams do
      resources :roosters
    end
  end

  resources :tournaments do
    resources :opponent_teams do
      resources :opponent_roosters
    end
  end

  resources :tournaments do
    resources :events do
      resources :team_line_ups
      resources :opponent_team_line_ups
    end
  end

  resources :tournaments do
    resources :events do
      get 'start', on: :member
      get 'resume', on: :member
      patch 'update_rooster_position', on: :member
      patch 'play', on: :member
    end
  end


  resources :tournaments do
    resources :invitations, only: [:new, :create]
  end
  
  resources :invitations, only: [:new, :create] do
    member do
      get 'accept'
    end
  end


resources :pitching_stats
resources :batting_stats
get 'my_events', to: 'events#my_events'


  root 'pages#home'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  get "/verify" => "verify#edit", :as => "verify"
  get "/verify" => "verify#new", :as => "new_verify"
  put "/verify" => "verify#update", :as => "update_verify"
  post "/verify" => "verify#create", :as => "resend_verify"
  resources :users, only: [:index,:destroy]
  
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  paginates_per 5

  belongs_to :user, :optional => true
  has_one_attached :image ,dependent: :destroy
  has_many :teams, dependent: :destroy
  has_many :opponent_teams, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :team_line_ups, dependent: :destroy
  has_many :invitations, dependent: :destroy
  has_many :opponent_team_line_ups, dependent: :destroy
  validates :name, :start_date, :end_date, :location, presence: true
  validates_presence_of :start_date, :end_date

  validate :end_date_is_after_start_date
  validate :start_date_cannot_be_in_the_past
  validate :name_and_location_cannot_start_with_numbers

  def start_date_cannot_be_in_the_past
    if start_date.present? && start_date.past?
      errors.add(:start_date, " can't be in the past")
    end
  end

  private

  def end_date_is_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, " cannot be before the start date")
    end
  end

  def name_and_location_cannot_start_with_numbers
    if name.present? && name.match?(/\A\d/)
      
      errors.add(:name, " cannot start with a number")
    end

    if location.present? && location.match?(/\A\d/)
      errors.add(:location, " cannot start with a number")
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: %i[ index show]
 
  before_action :set_tournament, only:[ :show, :edit, :update, :destroy ]

  def index
    @q = Tournament.ransack(params[:q])
    if current_user.nil?
      @tournaments = @q.result(distinct: true).page(params[:page]).per(5)
    elsif current_user&.roles&.exists?(role_name:'admin')
      @tournaments = @q.result(distinct: true).page(params[:page]).per(5)
    else
      user_tournaments = current_user.tournaments
      invited_tournaments = Tournament.joins(:invitations).where(invitations: { email: current_user.email, accepted: true })
      @tournaments = (user_tournaments + invited_tournaments).uniq
      @tournaments = @q.result(distinct: true).where(id: @tournaments.map(&:id)).page(params[:page]).per(5)
    end
  end

  def show
    ActiveStorage::Current.url_options = {
      host: request.base_url
    }
    @tournament = Tournament.find(params[:id])
    @team = @tournament.teams
    @opponent_team = @tournament.opponent_teams
    @event = @tournament.events
    @q_events = @tournament.events.ransack(params[:q])
    @events = @q_events.result(distinct: true)
    @q_teams = @tournament.teams.ransack(params[:q])
    @teams = @q_teams.result(distinct: true)
  end

  def new
    @tournament = Tournament.new
  end

  def edit
    @tournament = Tournament.find(params[:id])
  end

  def create
    @tournament = @current_user.tournaments.create(tournament_params)
    if @tournament.save
      flash[:notice] = "Tournament was successfully created."
      redirect_to tournaments_path
    else
      render "new"
    end
  end

  def update
    @tournament = Tournament.find(params[:id])
    if @tournament.update(tournament_params)
      flash[:notice] = "Tournament was successfully updated."
      redirect_to tournament_path
    else
      render "edit"
    end
  end

  def destroy
    @tournament = Tournament.find(params[:id])
    @tournament.destroy
    flash[:notice] = "Tournament was successfully deleted."
    redirect_to tournaments_path
  end

  private
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    def tournament_params
      params.require(:tournament).permit(:name, :start_date, :end_date, :location, :user_id, :image)
    end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
    <div class="border rounded p-4"> 
      <%= form_with model: @tournament, local: true do |form| %>

        <div class="form-group">
          <%= form.label :Name %><span class="required">*</span>
          <%= form.text_field :name, class: "form-control", autocomplete: 'off' %>
          <% if @tournament.errors[:Name].any? %>
          <div class="error-message", style="color: #f4340a;">
            <b><%= "Name" + @tournament.errors[:Name].join(", ") %></b>
          </div>
        <% end %>
        </div>

        <div class="form-group">
          <%= form.label :start_date %><span class="required" >*</span>
          <%= form.date_field :start_date, class: "form-control", autocomplete: 'off' %>
          <% if @tournament.errors[:start_date].any? %>
          <div class="error-message" , style="color: #f4340a;">
            <b><%= "start_date" + @tournament.errors[:start_date].join(" , ") %></b>
          </div>
        <% end %>
        </div>

        <div class="form-group">
          <%= form.label :end_date %><span class="required">*</span>
          <%= form.date_field :end_date, class: "form-control", autocomplete: 'off' %>
          <% if @tournament.errors[:end_date].any? %>
          <div class="error-message", style="color: #f4340a;">
            <b><%= "end_date" +" " +  @tournament.errors[:end_date].join(" , ") %></b>
          </div>
        <% end %>
        </div>

        <div class="form-group">
          <%= form.label :location %><span class="required">*</span>
          <%= form.text_field :location, class: "form-control", autocomplete: 'off' %>
          <% if @tournament.errors[:location].any? %>
          <div class="error-message", style="color: #f4340a;">
            <b><%= "location " + @tournament.errors[:location].join(" , ") %></b>
          </div>
        <% end %>
        </div>

        <div class="form-group">
          <%= form.label :image %>
          <%= form.file_field :image, class: "form-control-file" %>
        </div>

        
        <div class="row">
       
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <% if @tournament.persisted? %>
              <%= form.submit "Update", class: "btn btn-outline-primary " %>
            <% else %>
            <%= form.submit "Create", class: "btn btn-outline-primary " %>
            <% end %>
              <%= link_to "Back", tournaments_path(@tournament), class: "btn btn-outline-primary btn-sm" %>
            </div>
     
        </div>

      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tournaments/_tournament.html.erb
<div id="<%= dom_id tournament %>">
  <p>
    <strong>Name:</strong>
    <%= tournament.name %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= tournament.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= tournament.end_date %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= tournament.location %>
  </p>

</div>

app/views/tournaments/edit.html.erb
<h1 style="text-align:center"> Edit Tournament </h1> 



<%= render "form" %>

app/views/tournaments/index.html.erb
<div class="container mt-6">


  <div style="display: flex; align-items: center;">
    <%= image_tag("tournament.png", alt: "tournament", style: "width: 60px; height: 60px; object-fit: cover;") %>
    <h2 style="margin-left: 10px;">TOURNAMENTS</h2>
  </div>

  <div class="d-flex justify-content-between align-items-center mb-3">

  <%= search_form_for @q do |f| %>
    <%= f.search_field :name_cont %>
    <%= f.submit %>
  <% end %>
 

    <%= link_to new_tournament_path do %>
      <%= image_tag("add.png", alt: "profile", class: "img-fluid rounded-circle", style: "width: 40px; height: 40px; object-fit: cover;") %>
    <% end %>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>Tournament</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @tournaments.each do |tournament| %>
        <tr>
          <td>
            <strong><%= tournament.name %></strong><br>
            <%= tournament.start_date.strftime('%B %e, %Y') %>
            -
            <%= tournament.end_date.strftime('%B %e, %Y') %>
          </td>
          <td>
            <%= link_to tournament do %>
              <%= image_tag("show.png", alt: "show", style: "width: 20px; height: 20px; object-fit: cover;") %> |
            <% end %>
            <% if can? :update, tournament %>
              <%= link_to edit_tournament_path(tournament) do %>
                <%= image_tag("edit.png", alt: "edit", style: "width: 20px; height: 20px; object-fit: cover;") %> 
              <% end %>
            <% end %>

          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @tournaments %>
</div>

app/views/tournaments/new.html.erb
<h1 style="text-align:center"> New Tournament </h1> 
<%= render "form" %>

app/views/tournaments/show.html.erb
<div class="container mt-5">
    <div style="display: flex; align-items: center;">
        <%= image_tag("tournament.png", alt: "tournament", style: "width: 60px; height: 60px; object-fit: cover;") %>
        <h2 style="margin-left: 10px;">TOURNAMENT</h2>
        <%= link_to "Back", tournaments_path, style:"margin-left: 800px;" ,class: "btn btn-outline-primary" %>

    </div>


    <ul class="nav nav-tabs" id="tournamentTabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="overview-tab" data-toggle="tab" href="#overview" role="tab" aria-controls="overview" aria-selected="true">Overview</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="teams-tab" data-toggle="tab" href="#teams" role="tab" aria-controls="teams" aria-selected="false">Participating Teams</a>
        </li>

    </ul>

    <div class="tab-content mt-3">
        <div class="tab-pane fade show active" id="overview" role="tabpanel" aria-labelledby="overview-tab">
        <div class="d-flex justify-content-between align-items-center mb-12">

        <%= search_form_for @q_events, url: tournament_path(@tournament) do |f| %>
          
          <%= f.search_field :game_type_cont %>
          <%= f.submit "Search" %>
        <% end %>
        

        <% if can? :update, @tournament %>
            <%= link_to "New Event", new_tournament_event_path(@tournament,@event), style:"margin-left: 600px;",class: "btn btn-success" %><br/>
        <% end %>


    </div>    
        <div class="card">
                <div class="card-body">
                    <%= render @tournament %>
                    <div class="profile-picture" style="float: right;margin-top: -130px;margin-right: 200px;">
                    <%= image_tag @tournament.image.url, alt: "Profile Picture", style:"height: 100px;" if @tournament.image.attached? %>
                  </div>
                    <div class="mt-3">
                        <div class="inline-button">
                            <% if can? :update, @tournament %>
                                <%= link_to edit_tournament_path(@tournament) do %>
                                    <%= image_tag("edit.png", alt: "edit", style: "width: 20px; height: 20px; object-fit: cover;") %> |
                                <% end %>
                            <% end %>
                            <% if can? :update, @tournament %>
                            <%= link_to new_tournament_invitation_path(@tournament) do %>
                              <%= image_tag("invite.png", alt: "edit", style: "width: 20px; height: 20px; object-fit: cover;") %> |
                              <%#= button_to "Invite", tournament, class: "btn btn-secondary btn-sm" %>
                              <% end %>
                              <% end %>
                            <% if can? :update, @tournament %>
                                <%= link_to new_tournament_team_path(@tournament) do %>
                                    <%= image_tag("addteam.png", alt: "edit", style: "width: 20px; height: 20px; object-fit: cover;") %> |
                                <% end %>
                                <%= link_to new_tournament_opponent_team_path(@tournament) do %>
                                    <%= image_tag("opponent.png", alt: "edit", style: "width: 20px; height: 20px; object-fit: cover;") %> |
                                <% end %>
                            <% end %>



                            <% if can? :destroy, @tournament %>
                            <div style=" margin-left: 130px; margin-top: -25px;">
                                <%= button_to tournament_path(@tournament), method: :delete, data: { confirm: "Are you sure?" }, class: "myButton" do %>
                                <%= image_tag("empty.png", alt: "edit", style: "width: 20px; height: 20px; object-fit: cover;") %>
                            </div>
                                <% end %>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
            <div style="max-height: 300px; overflow-y: auto;">
            <table class="table">
                <thead>
                    <tr>
                        <th>Events</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                <% @events.each do |event| %>
                  <tr>
                    <td>
                      <p><%= event.game_type %></p>
                    </td>
                    <td>
                      <%= link_to tournament_event_path(@tournament, event) do %>
                        <%= image_tag("show.png", alt: "show", style: "width: 20px; height: 20px; object-fit: cover;") %> |
                      <% end %>
                      <%= link_to edit_tournament_event_path(@tournament, event) do %>
                        <%= image_tag("edit.png", alt: "show", style: "width: 20px; height: 20px; object-fit: cover;") %> |
                      <% end %>
                      <div style=" margin-left:65px; margin-top: -25px;">
                      <%= button_to tournament_event_path(@tournament, event), method: :delete, data: { confirm: "Are you sure?" } do %>
                        <%= image_tag("empty.png", alt: "delete", style: "width: 20px; height: 20px; object-fit: cover;") %>
                      <% end %>
                      </div>
                    </td>
                  </tr>
                <% end %>
              </tbody>
              
            </table>
            </div>
        </div>

        <div class="tab-pane fade" id="teams" role="tabpanel" aria-labelledby="teams-tab">
            <div class="card">
                <div class="card-body">
                    <h3>Participating Teams</h3>
                    <div>
                        <%= search_form_for @q_teams ,url:tournament_path(@tournament) do |f| %>
                                <%= f.search_field :name_cont %>
                            <%= f.submit "Search" %>
                        <% end %>
                    </div>  
                    <div style="max-height: 400px; overflow-y: auto;">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Teams</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @teams.each do |team| %>
                                <tr>
                                    <td>
                                        <p><%= team.name %></p>
                                    </td>
                                    <td>
                                        <%= link_to tournament_team_path(@tournament, team) do %>
                                            <%= image_tag("show.png", alt: "show", style: "width: 20px; height: 20px; object-fit: cover;") %>
                                        <% end %>
                                    </td>
                                </tr>
                            <% end %>

                            <% @tournament.opponent_teams.each do |opponent_team| %>
                                <tr>
                                    <td>
                                        <p><%= opponent_team.name %></p>
                                    </td>
                                    <td>
                                        <%= link_to tournament_opponent_team_path(@tournament, opponent_team) do %>
                                            <%= image_tag("show.png", alt: "show", style: "width: 20px; height: 20px; object-fit: cover;") %>
                                        <% end %>
                                    </td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>

        


    </div>
</div>

<script>
    $(document).ready(function() {
        $('#tournamentTabs a').on('click', function (e) {
            e.preventDefault()
            $(this).tab('show')
        })
    });
</script>