config/routes.rb
Rails.application.routes.draw do

  resources :tournaments do
    get 'search', on: :collection
  end
  
  resources :tournaments do
    resources :teams do
      resources :roosters
    end
  end

  resources :tournaments do
    resources :opponent_teams do
      resources :opponent_roosters
    end
  end

  resources :tournaments do
    resources :events do
      resources :team_line_ups
      resources :opponent_team_line_ups
    end
  end

  resources :tournaments do
    resources :events do
      get 'start', on: :member
      get 'resume', on: :member
      patch 'update_rooster_position', on: :member
      patch 'play', on: :member
    end
  end


  resources :tournaments do
    resources :invitations, only: [:new, :create]
  end
  
  resources :invitations, only: [:new, :create] do
    member do
      get 'accept'
    end
  end


resources :pitching_stats
resources :batting_stats
get 'my_events', to: 'events#my_events'


  root 'pages#home'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  get "/verify" => "verify#edit", :as => "verify"
  get "/verify" => "verify#new", :as => "new_verify"
  put "/verify" => "verify#update", :as => "update_verify"
  post "/verify" => "verify#create", :as => "resend_verify"
  resources :users, only: [:index,:destroy]
  
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :tournament
  belongs_to :team, :optional => true
  has_one_attached :image 
  belongs_to :opponent_team, :optional => true
  has_many :team_line_ups, dependent: :destroy
  has_many :moves
  has_many :opponent_team_line_ups
  has_many :scoreboards, dependent: :destroy
  has_many :event_setup, dependent: :destroy
  has_many :event_innings, dependent: :destroy
  belongs_to :rooster_position,:optional => true
  has_many :batting_stats	, dependent: :destroy
  has_many :pitching_stats, dependent: :destroy	

  validates :game_type, :start_date,:location, presence: true
  validate :start_date_cannot_be_in_the_past
  validate :start_date_within_tournament_dates

  def start_date_cannot_be_in_the_past
    if start_date.present? && start_date.past?
      errors.add(:start_date, "can't be in the past")
    end
  end  

  def start_date_within_tournament_dates
    unless tournament.nil? || (start_date >= tournament.start_date && start_date <= tournament.end_date)
      errors.add(:start_date, " must be between tournament's start date and end date")
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    [ "game_type"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["image_attachment", "image_blob", "opponent_team", "opponent_team_line_ups", "team", "team_line_ups", "tournament", "user"]
  end



end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[ index show]

  load_and_authorize_resource
    before_action :find_event_by_id, only: %i[ show edit update destroy start ]
    before_action :set_tournament

  def start
    if @event.is_live?
    elsif !@event.is_live? && @event.event_innings.exists?(inning_number: 9)
      flash[:notice] = "Event is Over."
    else
      flash[:notice] = "Event is started."
      StartEventService.new(find_event_by_id, current_user).call
    end

    @rooster_position = RoosterPosition.find_by(scoreboard_id: @event.scoreboards.last.id)
  
    render 'start'
  end

  def resume
    @event = find_event_by_id
    render 'start'
  end

  def play

      PlayEventService.new(find_event_by_id, event_params[:move_id],current_user).call
      redirect_to start_tournament_event_path(@tournament, @event)
    
  end
  

  def index
    @q_events = Event.ransack(params[:q])
    if current_user.nil?
      @event =  @q_events.result(distinct: true).all
    else
      @event =  @q_events.result(distinct: true).where(user_id:current_user.id)
    end
  end


  def show
    @tournament = Tournament.find(params[:tournament_id])
    @event = @tournament.events.find(params[:id])
    @team_line_ups = @event.team_line_ups
    @opponent_team_line_ups = @event.opponent_team_line_ups
    total_positions = Position.count
    team_line_up_positions_filled = @team_line_ups.pluck(:position_id).uniq.count
    opponent_team_line_up_positions_filled = @opponent_team_line_ups.pluck(:position_id).uniq.count
    if team_line_up_positions_filled == total_positions && opponent_team_line_up_positions_filled == total_positions
      @show_start_button = true
    else
      @show_start_button = false
    end
  
    if @event.is_live.present?
      @show_resume_button = true
    else
      @show_resume_button = false
    end
  
    flash.now[:notice] = flash[:notice] if flash[:notice].present?
    @team = @event.team
    @opponent_team = @event.opponent_team
    @show_modal = !@team.roosters.exists?(user_id: current_user.id)
    @show_modal1 = !@opponent_team.opponent_roosters.exists?(user_id: current_user.id)
  end
  
  def my_events
    @events = current_user.events
    # @events = current_user.tournaments.events.find(params[:id])
  end
  

  def new
    @tournament = Tournament.find(params[:tournament_id])
    @event = Event.new
  end
  
  def edit
    @tournament = Tournament.find(params[:tournament_id])
    @event = @tournament.events.find(params[:id])
  end

  def create
    @event = current_user.events.build(event_params.merge(tournament_id: @tournament.id))
    if @event.save
      flash[:notice] = "Event was successfully created."
      redirect_to tournament_event_path(@tournament, @event)
    else
      render "new"
    end
  end
  

  def update
    if @event.update(event_params)
      flash[:notice] = "Event was successfully updated."
      redirect_to tournament_event_path(@tournament, @event)
    else
      render "edit"
    end
  end
  

  def destroy
    @event.destroy
    flash[:notice] = "Event was successfully deleted."
    redirect_to tournament_path(@tournament)
  end
  


  private
    def find_event_by_id
      Event.find(params[:id])
    end

    def set_tournament
      return unless params[:tournament_id].present?
  
      @tournament = Tournament.find(params[:tournament_id])
    end

    def event_params
      params.require(:event).permit(:game_type,:name,:team_id,:opponent_team_id,:location,:start_date,:belongs ,:memo, :image, :move_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>game_type</strong>
    <%= event.game_type %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= event.start_date %>
  </p>


  <p>
    <strong>Location:</strong>
    <%= event.location %>
  </p>

</div>

app/views/events/_form.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
    <div class="border rounded p-4"> 
      <%= form_with model: [@tournament, @event] do |form| %>

        <div class="form-group">
          <%= form.label :game_type %><span class="required">*</span>
          <%= form.text_field :game_type, class: "form-control", required: true, autocomplete: "off" %>
          <% if @event.errors[:game_type].any? %>
          <div class="error-message", style="color: #f4340a;">
            <b><%= "game_type  " + @event.errors[:game_type].join(", ") %></b>
          </div>
        <% end %>
        </div>

        <div class="form-group">
          <%= form.label :team_id %><span class="required">*</span>
          <%= form.collection_select :team_id, @tournament.teams.all, :id, :name, { prompt: "Select home_team" }, class: "form-control", required: true, autocomplete: "off" %>
          <% if @event.errors[:team_id].any? %>
          <div class="error-message", style="color: #f4340a;">
            <b><%= "team_id  " + @event.errors[:team_id].join(", ") %></b>
          </div>
        <% end %>
          </div>

        <div class="form-group">
          <%= form.label :opponent_team_id %><span class="required">*</span>
          <%= form.collection_select :opponent_team_id, @tournament.opponent_teams.all, :id, :name, { prompt: "Select away_team" }, class: "form-control", required: true, autocomplete: "off" %>
          <% if @event.errors[:opponent_team_id].any? %>
          <div class="error-message", style="color: #f4340a;">
            <b><%= "opponent_team_id  " + @event.errors[:opponent_team_id].join(", ") %></b>
          </div>
        <% end %>
          </div>

        <div class="form-group">
          <%= form.label :location %><span class="required">*</span>
          <%= form.text_field :location, class: "form-control", required: true, autocomplete: "off" %>
          <% if @event.errors[:location].any? %>
          <div class="error-message", style="color: #f4340a;">
            <b><%= "location  " + @event.errors[:location].join(", ") %></b>
          </div>
        <% end %>
        </div>

        <div class="form-group">
          <%= form.label :start_date %><span class="required">*</span>
          <%= form.date_field :start_date, class: "form-control", required: true, autocomplete: "off" %>
          <% if @event.errors[:start_date].any? %>
          <div class="error-message", style="color: #f4340a;">
            <b><%= "start_date  " + @event.errors[:start_date].join(", ") %></b>
          </div>
        <% end %>
        </div>

        <div class="form-group">
          <%= form.label :belongs %>
          <%= form.number_field :belongs, class: "form-control", autocomplete: "off" %>
        </div>

        <div class="form-group">
          <%= form.label :memo %>
          <%= form.text_field :memo, class: "form-control", autocomplete: "off" %>
        </div>


        <div class="row">
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <% if @event.persisted? %>
        <%= form.submit "Update", class: "btn btn-outline-primary " %>
      <% else %>
      <%= form.submit "Create", class: "btn btn-outline-primary " %>
      <% end %>
          <%= link_to "Back", tournament_path(@tournament), class: "btn btn-outline-primary btn-sm" %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<h1 style="text-align:center"> Edit Event </h1> 

<%= render "form" %>

app/views/events/index.html.erb
<div class="container mt-6">
  <h1 class="text-center mb-4">EVENTS</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.game_type %></td>
          <td>
          <%= link_to tournament_event_path(@tournament, event) do %>
            <%= image_tag("show.png", alt: "show", style: "width: 20px; height: 20px; object-fit: cover;") %> |
          <% end %> 
          <%= link_to edit_tournament_event_path(@tournament, event) do %>
            <%= image_tag("edit.png", alt: "show", style: "width: 20px; height: 20px; object-fit: cover;") %> |
        <% end %> 
        <div style=" margin-left: 60px; margin-top: -25px;">
        <%= button_to tournament_event_path(@tournament,event), method: :delete, data: { confirm: "Are you sure?" }, class: "myButton" do %>
        <%= image_tag("empty.png", alt: "edit", style: "width: 20px; height: 20px; object-fit: cover;") %>
        <% end %>
        </div>
         </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/events/my_events.html.erb
<div class="container">
  <h1>My Events</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Game Type</th>
        <th>Start Date</th>
      </tr>
    </thead>
    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.game_type %>
          <td><%= event.start_date %>
        
      </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/events/new.html.erb
<h1 style="text-align:center"> New Event </h1> 


<%= render "form" %>

app/views/events/resume.html.erb
<div class="d-flex justify-content-between align-items-center mb-3">
<h1><%= @event.team.name %> vs <%= @event.opponent_team.name %></h1>
<%= link_to "Back", tournament_path(@tournament), style:"margin-right: 20px;" ,class: "btn btn-outline-primary" %>
</div>
  <div style="max-width: 100%; display: flex;">

    <div style="flex: 60%; padding: 260px; background-image: url('<%= asset_path('Field.png') %>'); background-size: 100% 100%; background-repeat: no-repeat;">
    </div>
    <div style="flex: 40%;">
      <div class="container">

      <% if @event.is_live.nil? %>
      <%= link_to "START", start_tournament_event_path(@tournament, @event), style: "margin-left: 10px;", class: "btn btn-outline-primary" %>
    <% else %>
      <%= link_to "RESUME", start_tournament_event_path(@tournament, @event), style: "margin-left: 10px;", class: "btn btn-outline-primary" %>
    <% end %>
    
        
        <div style="display: flex; align-items: center;">
          <h4 style="margin-left: 10px;">TeamLineUp</h4> 
          
          <%= link_to tournament_event_team_line_ups_path(@event.tournament, @event) do %>
            <%= image_tag("check.jpg", alt: "completed", style: "width: 25px; height: 25px; object-fit: cover; margin-left: 20px;") %>
          <% end %>
         
           <%= link_to new_tournament_event_team_line_up_path(@event.tournament, @event) do %>
            <%= image_tag("lineup.png", alt: "teamlineup", style: "width: 25px; height: 25px; object-fit: cover;margin-left: 20px;") %>
          <% end %>
         
        </div>

        <div style="display: flex; align-items: center;">
          <h4 style="margin-left: 10px;">Opponent Teamlineup</h4> 

          
          <%= link_to tournament_event_opponent_team_line_ups_path(@event.tournament, @event) do %>
            <%= image_tag("check.jpg", alt: "completed", style: "width: 25px; height: 25px; object-fit: cover; margin-left: 20px;") %>
          <% end %>
          
          <%= link_to new_tournament_event_opponent_team_line_up_path(@event.tournament, @event) do %>
            <%= image_tag("lineup.png", alt: "tournament", style: "width: 25px; height: 25px; object-fit: cover;margin-left: 20px;") %>
          <% end %>
          
        </div>
                
      </div>
    </div>
  </div>

app/views/events/show.html.erb
<div class="d-flex justify-content-between align-items-center mb-3">
<h1><%= @event.team.name %> vs <%= @event.opponent_team.name %></h1>
<%= link_to "Back", tournament_path(@tournament),style:"margin-right: -700px;" ,class: "btn btn-outline-primary" %>
<%= link_to "Edit",edit_tournament_event_path(@tournament, @event) , style:"margin-right: -700px;" ,class: "btn btn-outline-primary"%>
<%= button_to "Delete", tournament_event_path(@tournament, @event) , style:"margin-right: 20px;",class: "btn btn-outline-primary",method: :delete, data: { confirm: "Are you sure?" } %>

</div>
</div>
  <div style="max-width: 100%; display: flex;">

    <div style="flex: 60%; padding: 260px; background-image: url('<%= asset_path('Field.png') %>'); background-size: 100% 100%; background-repeat: no-repeat;">
    </div>
    <div style="flex: 40%;">
      <div class="container">
     
        <% @o8 = @event.event_innings.where(inning_number: 9,bottom:true).ids %>
        <% if @event.scoreboards.where(event_inning_id: @o8).last&.out == 3 %>
          <%= link_to "RESTART", start_tournament_event_path(@tournament, @event), style: "margin-left: 10px;", class: "btn btn-outline-primary" %>
        <% elsif @show_resume_button %>
          <%= link_to "RESUME", resume_tournament_event_path(@tournament, @event), style: "margin-left: 10px;", class: "btn btn-outline-primary" %>
        <% elsif @show_start_button %>
          <%= link_to "START", start_tournament_event_path(@tournament, @event), style: "margin-left: 10px;", class: "btn btn-outline-primary" %>
        <% end %>
    

    <% if false %>
      <% if @event.is_live.nil? && @team_line_up_complete && @opponent_team_line_up_complete %>
      <%= link_to "START", start_tournament_event_path(@tournament, @event), style: "margin-left: 10px;", class: "btn btn-outline-primary" %>
      <% elsif @event.is_live.present? && @team_line_up_complete && @opponent_team_line_up_complete %>
        <%= link_to "RESUME", resume_tournament_event_path(@tournament, @event), style: "margin-left: 10px;", class: "btn btn-outline-primary" %>
      <% end %>
        <div style="display: flex; align-items: center;">
          <h4 style="margin-left: 10px;">TeamLineUp</h4> 
          <% if @event.is_live.nil? %>
          <%= link_to new_tournament_event_team_line_up_path(@event.tournament, @event) do %>
            <%= image_tag("lineup.png", alt: "teamlineup", style: "width: 25px; height: 25px; object-fit: cover;margin-left: 20px;") %>
            <% end %>
            <% else %>        
            <%= link_to tournament_event_team_line_ups_path(@event.tournament, @event) do %>
              <%= image_tag("check.jpg", alt: "completed", style: "width: 25px; height: 25px; object-fit: cover; margin-left: 20px;") %>
              <% end %>
            <% end %>
        </div>
        <div style="display: flex; align-items: center;">
          <h4 style="margin-left: 10px;">Opponent Teamlineup</h4> 
          <% if @event.is_live.nil? %>
          <%= link_to new_tournament_event_opponent_team_line_up_path(@event.tournament, @event) do %>
            <%= image_tag("lineup.png", alt: "tournament", style: "width: 25px; height: 25px; object-fit: cover;margin-left: 20px;") %>
          <% end %>
          <% else %> 
          <%= link_to tournament_event_opponent_team_line_ups_path(@event.tournament, @event) do %>
            <%= image_tag("check.jpg", alt: "completed", style: "width: 25px; height: 25px; object-fit: cover; margin-left: 20px;") %>
          <% end %>
          <% end %>
    <% end %>   
    
      <div style="display: flex; align-items: center;">
        <h4 style="margin-left: 10px;">TeamLineUp</h4> 
        <% if @show_start_button %>
        <%= link_to tournament_event_team_line_ups_path(@event.tournament, @event) do %>
        <%= image_tag("check.jpg", alt: "completed", style: "width: 25px; height: 25px; object-fit: cover; margin-left: 20px;") %>
        <% end %>

        <% else %>        
        <%= link_to new_tournament_event_team_line_up_path(@event.tournament, @event) do %>
          <%= image_tag("lineup.png", alt: "teamlineup", style: "width: 25px; height: 25px; object-fit: cover;margin-left: 20px;") %> |
          <% end %>
          <%= link_to new_tournament_team_rooster_path(@team.tournament, @team) do %>
            <%= image_tag("addroaster.png", alt: "edit", style: "width: 25px; height: 25px; object-fit: cover;") %> 
            <% end %>

        <% end %>
      </div>

      <div style="display: flex; align-items: center;">
        <h4 style="margin-left: 10px;">Opponent Teamlineup</h4> 
        <% if @show_start_button %>
        <%= link_to tournament_event_opponent_team_line_ups_path(@event.tournament, @event) do %>
          <%= image_tag("check.jpg", alt: "completed", style: "width: 25px; height: 25px; object-fit: cover; margin-left: 20px;") %>
        <% end %>
        <% else %> 
        <%= link_to new_tournament_event_opponent_team_line_up_path(@event.tournament, @event) do %>
          <%= image_tag("lineup.png", alt: "tournament", style: "width: 25px; height: 25px; object-fit: cover;margin-left: 20px;") %> |
        <% end %>
        <%= link_to new_tournament_opponent_team_opponent_rooster_path(@opponent_team.tournament, @opponent_team) do %> 
          <%= image_tag("addroaster.png", alt: "edit", style: "width: 25px; height: 25px; object-fit: cover;") %> 
          <% end %>
       <% end %>   
      </div>
                
      </div>
    </div>

    <div class="modal fade" id="addRoasterModal" tabindex="-1" aria-labelledby="addRoasterModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="addRoasterModalLabel">Reminder!</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Add a roaster to the team before accessing the team lineup.</p>
        </div>
      </div>
    </div>
  </div>
  
  <div class="modal fade" id="addRoasterModal1" tabindex="-1" aria-labelledby="addRoasterModal1Label" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="addRoasterModal1Label">Reminder!</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Add an opponent roaster to the opponent team before accessing the opponent team lineup.</p>
        </div>
      </div>
    </div>
  </div>
  


  </div>

  <script>
  document.addEventListener("DOMContentLoaded", function() {
    <% if @show_modal %>
      $('#addRoasterModal').modal('show');
    <% elsif @show_modal1 %>
      $('#addRoasterModal1').modal('show');
    <% end %>
  });
</script>