config/routes.rb
Rails.application.routes.draw do

  resources :tournaments do
    get 'search', on: :collection
  end
  
  resources :tournaments do
    resources :teams do
      resources :roosters
    end
  end

  resources :tournaments do
    resources :opponent_teams do
      resources :opponent_roosters
    end
  end

  resources :tournaments do
    resources :events do
      resources :team_line_ups
      resources :opponent_team_line_ups
    end
  end

  resources :tournaments do
    resources :events do
      get 'start', on: :member
      get 'resume', on: :member
      patch 'update_rooster_position', on: :member
      patch 'play', on: :member
    end
  end


  resources :tournaments do
    resources :invitations, only: [:new, :create]
  end
  
  resources :invitations, only: [:new, :create] do
    member do
      get 'accept'
    end
  end


resources :pitching_stats
resources :batting_stats
get 'my_events', to: 'events#my_events'


  root 'pages#home'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  get "/verify" => "verify#edit", :as => "verify"
  get "/verify" => "verify#new", :as => "new_verify"
  put "/verify" => "verify#update", :as => "update_verify"
  post "/verify" => "verify#create", :as => "resend_verify"
  resources :users, only: [:index,:destroy]
  
end

app/models/opponent_rooster.rb
class OpponentRooster < ApplicationRecord
  belongs_to :user
  belongs_to :opponent_team
  has_one_attached :image ,dependent: :destroy
  validates :name, :jersey_number, presence: true
  has_many :batting_stats	, dependent: :destroy
  has_many :pitching_stats, dependent: :destroy	



end

app/controllers/opponent_roosters_controller.rb
class OpponentRoostersController < ApplicationController
    before_action :authenticate_user!, except: %i[ index show]
    load_and_authorize_resource
    before_action :set_opponent_rooster, only: %i[ show update destroy ]
    before_action :authenticate_user!, except: %i[ index]
    before_action :set_opponent_team
    before_action :set_tournament

    def new
        @tournament = Tournament.find(params[:tournament_id])
        @opponent_team = OpponentTeam.find(params[:opponent_team_id])
        @opponent_rooster = OpponentRooster.new
    end

def index
    if current_user.nil?
      @opponent_rooster = OpponentRooster.all
    else
      @opponent_rooster = OpponentRooster.where(user_id:current_user.id)
    end
end

def show
    @tournament = Tournament.find(params[:tournament_id])
    @opponent_team = OpponentTeam.find(params[:opponent_team_id])
    @opponent_rooster = @opponent_team.opponent_roosters.find(params[:id])
    ActiveStorage::Current.url_options = {
        host: request.base_url
      }
end



def create
    @opponent_rooster = current_user.opponent_roosters.build(opponent_rooster_params.merge(opponent_team_id:@opponent_team.id ).merge(tournament_id:@tournament.id))
    if @opponent_rooster.save
      flash[:notice] = "Opponent Rooster was successfully created."
      redirect_to tournament_opponent_team_path(@tournament, @opponent_team)
    else
      render "new"
    end
end

def update
    if @opponent_rooster.update(opponent_rooster_params)
      flash[:notice] = "Opponent Rooster was successfully updated."
      redirect_to tournament_opponent_team_rooster_path(@tournament,@team,opponent_rooster)
    else
      render "edit"
    end
end

def destroy
    @opponent_rooster.destroy
    flash[:notice] = "Rooster was successfully deleted."
  redirect_to tournament_opponent_team_path(@tournament, @opponent_team)
end

  private

    def set_opponent_rooster
      @opponent_rooster = OpponentRooster.find(params[:id])
    end

    def set_opponent_team
        @opponent_team = OpponentTeam.find(params[:opponent_team_id])
    end

    def set_tournament
        @tournament = Tournament.find(params[:tournament_id])
      end

    def opponent_rooster_params
      params.require(:opponent_rooster).permit(:name, :jersey_number, :image)
   
    end

end

app/helpers/opponent_rooster_helper.rb
module OpponentRoosterHelper
end

app/views/opponent_roosters/_form.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="border rounded p-4">
        <%= form_with(model: [@tournament, @opponent_team, @opponent_rooster], path: tournament_opponent_team_opponent_roosters_path(@tournament, @opponent_team)) do |form| %>
          <div class="form-group">
            <%= form.label :full_name %><span class="required">*</span>
            <%= form.text_field :name, class: "form-control", autocomplete: 'off' %>
            <% if @opponent_rooster.errors[:name].any? %>
            <div class="error-message", style="color: #f4340a;">
              <b><%= "name " + @opponent_rooster.errors[:name].join(", ") %></b>
            </div>
          <% end %>
          </div>
          <div class="form-group">
            <%= form.label :jersey_number %><span class="required">*</span>
            <%= form.number_field :jersey_number, class: "form-control", autocomplete: 'off' %>
            <% if @opponent_rooster.errors[:jersey_number].any? %>
            <div class="error-message", style="color: #f4340a;">
              <b><%= "jersey_number " + @opponent_rooster.errors[:jersey_number].join(", ") %></b>
            </div>
          <% end %>
          </div>
          <div class="form-group">
            <%= form.label :image %>
            <%= form.file_field :image, class: "form-control-file" %>
          </div>

          <div class="row">
          <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <% if @opponent_rooster.persisted? %>
                <%= form.submit "Update", class: "btn btn-outline-primary " %>
                <% else %>
                <%= form.submit "Create", class: "btn btn-outline-primary " %>
            <% end %>
              <%= link_to "Back", tournament_path(@tournament), class: "btn btn-outline-primary btn-sm" %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/opponent_roosters/edit.html.erb
<h1> Edit Roaster </h1>

<%= render "form" %>

app/views/opponent_roosters/index.html.erb
<h1>Roosters</h1>
<% if false %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Jersey Number</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @roosters.each do |rooster| %>
      <tr>
        <td><%= rooster.name %></td>
        <td><%= rooster.jersey_number %></td>
        <td>
          <%= link_to 'Show', tournament_team_rooster_path(@tournament,@team, rooster) %>
          <%= link_to 'Edit', edit_team_rooster_path(@tournament,@team, rooster) %>
          <%= link_to 'Destroy', team_rooster_path(@tournament,@team, rooster), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rooster', new_tournament_team_rooster_path(@rooster) %>
<% end %>

app/views/opponent_roosters/new.html.erb
<h1 style="text-align:center"> New Opponent Roaster </h1> 

<%= render "form" %>

app/views/opponent_roosters/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-6">
      <h2>Opponent Rooster Details</h2>
      <div class="profile-picture">
        <%= image_tag @opponent_rooster.image.url, alt: "Profile Picture", style:"height: 50px;" if @opponent_rooster.image.attached? %>
      </div>
      <div class="profile-details">
        <p>
          Name: <%= @opponent_rooster.name %><br>
          Jersey Number: <%= @opponent_rooster.jersey_number %><br>
        </p>
      </div>

     
        <div class="btn-group" role="group" aria-label="Opponent Rooster Actions">
          <%= link_to edit_tournament_opponent_team_opponent_rooster_path(@tournament, @opponent_team, @opponent_rooster), class: "btn btn-sm btn-outline-primary" do %>
            <%= image_tag("edit.png", alt: "edit", style: "width: 20px; height: 20px; object-fit: cover;") %> Edit
          <% end %>

          <%= button_to tournament_opponent_team_opponent_rooster_path(@tournament, @opponent_team, @opponent_rooster), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-outline-danger", style: "margin-left: 10px;" do %>
            <%= image_tag("empty.png", alt: "delete", style: "width: 20px; height: 20px; object-fit: cover;") %> Destroy
          <% end %>

          <%= link_to tournament_opponent_team_path(@tournament, @opponent_team), class: "btn btn-sm btn-outline-primary" do %>
            <%= image_tag("back.png", alt: "back", style: "width: 20px; height: 20px; object-fit: cover;") %> Back to Team
          <% end %>
        </div>
      
    </div>
  </div>
</div>